const albums = [
  {
    albumTitle: "An Evening with Silk Sonic",
    releaseYear: 2021,
    artistName: "Silk Sonic",
    bandMembers: [
      { memberName: "Bruno Mars" },
      { memberName: "Anderson .Paak" },
    ],
    tracks: [
      { trackTitle: "Silk Sonic Intro", trackNumber: 1, duration: "63" },
      { trackTitle: "Leave The Door Open", trackNumber: 2, duration: "242" },
      { trackTitle: "Fly As Me", trackNumber: 3, duration: "219" },
      { trackTitle: "After Last Night", trackNumber: 4, duration: "249" },
      { trackTitle: "Smokin Out The Window", trackNumber: 5, duration: "197" },
      { trackTitle: "Put On A Smile", trackNumber: 6, duration: "255" },
      { trackTitle: "777", trackNumber: 7, duration: "165" },
      { trackTitle: "Skate", trackNumber: 8, duration: "203" },
      { trackTitle: "Love's Train", trackNumber: 9, duration: "307" },
      { trackTitle: "Blast Off", trackNumber: 10, duration: "284" },
    ],
  },
  {
    albumTitle: "Pearl",
    releaseYear: 1971,
    artistName: "Janis Joplin",
    bandMembers: [{ memberName: "" }],
    tracks: [
      { trackTitle: "Move Over", trackNumber: 1, duration: "219" },
      { trackTitle: "Cry Baby", trackNumber: 2, duration: "236" },
      { trackTitle: "A Woman Left Loney", trackNumber: 3, duration: "207" },
      { trackTitle: "Half Moon", trackNumber: 4, duration: "231" },
      {
        trackTitle: "Buried Alive In The Blues",
        trackNumber: 5,
        duration: "144",
      },
      { trackTitle: "My Baby", trackNumber: 6, duration: "244" },
      { trackTitle: "Me and Bobby McGee", trackNumber: 7, duration: "269" },
      { trackTitle: "Mercedes Benz", trackNumber: 8, duration: "106" },
      { trackTitle: "Trust Me", trackNumber: 9, duration: "195" },
      { trackTitle: "Get It While You Can", trackNumber: 10, duration: "203" },
    ],
  },
  {
    albumTitle: "Ain't That Good News",
    releaseYear: 1964,
    artistName: "Sam Cooke",
    bandMembers: [{ memberName: "" }],
    tracks: [
      { trackTitle: "Ain't That Good News", trackNumber: 1, duration: "2:28" },
      {
        trackTitle: "Meet Me At Mary's Place",
        trackNumber: 2,
        duration: "2:40",
      },
      { trackTitle: "Good Times", trackNumber: 3, duration: "2:25" },
      {
        trackTitle: "Rome Wasn't Built In A Day",
        trackNumber: 4,
        duration: "2:30",
      },
      {
        trackTitle: "Another Saturday Night",
        trackNumber: 5,
        duration: "2:27",
      },
      { trackTitle: "Tennessee Waltz", trackNumber: 6, duration: "3:10" },
      {
        trackTitle: "A Change Is Gonna Come",
        trackNumber: 7,
        duration: "3:10",
      },
      { trackTitle: "Falling In Love", trackNumber: 8, duration: "2:40" },
      { trackTitle: "Home", trackNumber: 9, duration: "2:27" },
      { trackTitle: "Sittin' In The Sun", trackNumber: 10, duration: "3:12" },
      { trackTitle: "No Second Time", trackNumber: 11, duration: "3:00" },
      { trackTitle: "The Riddle Song", trackNumber: 12, duration: "2:28" },
    ],
  },
  {
    albumTitle: "Greatest Hits",
    releaseYear: 2009,
    artistName: "Foo Fighters",
    bandMembers: [
      { memberName: "Dave Grohl" },
      { memberName: "Pat Smear" },
      { memberName: "Nate Mendel" },
      { memberName: "Taylor Hawkins" },
      { memberName: "Chris Shiflett" },
    ],
    tracks: [
      { trackTitle: "All My Life", trackNumber: 1, duration: "4:24" },
      { trackTitle: "Best Of You", trackNumber: 2, duration: "4:16" },
      { trackTitle: "Everlong", trackNumber: 3, duration: "4:10" },
      { trackTitle: "The Pretender", trackNumber: 4, duration: "4:27" },
      { trackTitle: "My Hero", trackNumber: 5, duration: "4:19" },
      { trackTitle: "Learn To Fly", trackNumber: 6, duration: "3:56" },
      { trackTitle: "Times Like These", trackNumber: 7, duration: "4:28" },
      { trackTitle: "Monkey Wrench", trackNumber: 8, duration: "3:53" },
      { trackTitle: "Big Me", trackNumber: 9, duration: "2:14" },
      { trackTitle: "Breakout", trackNumber: 10, duration: "3:22" },
      { trackTitle: "Long Road To Ruin", trackNumber: 11, duration: "3:48" },
      { trackTitle: "This Is A Call", trackNumber: 12, duration: "3:55" },
      { trackTitle: "Skin And Bones", trackNumber: 13, duration: "4:04" },
      { trackTitle: "Wheels", trackNumber: 14, duration: "4:38" },
      { trackTitle: "Word Forward", trackNumber: 15, duration: "3:49" },
      { trackTitle: "Everlong (Acoustic)", trackNumber: 16, duration: "4:11" },
    ],
  },
  {
    albumTitle: "Funky Divas",
    releaseYear: 1992,
    artistName: "En Vogue",
    bandMembers: [
      { memberName: "Terry Ellis" },
      { memberName: "Cindy Herron" },
      { memberName: "Maxine Jones" },
      { memberName: "Dawn Robinson" },
    ],
    tracks: [
      { trackTitle: "This Is Your Life", trackNumber: 1, duration: "5:05" },
      {
        trackTitle: "My Lovin' (You're Never Gonna Get It)",
        trackNumber: 2,
        duration: "4:42",
      },
      { trackTitle: "Hip Hop Lover", trackNumber: 3, duration: "5:13" },
      { trackTitle: "Free Your Mind", trackNumber: 4, duration: "4:52" },
      { trackTitle: "Desire", trackNumber: 5, duration: "4:01" },
      {
        trackTitle: "Giving Him Something He Can Feel",
        trackNumber: 6,
        duration: "3:56",
      },
      {
        trackTitle: "It Ain't Over Till The Fat Lady Sings",
        trackNumber: 7,
        duration: "4:13",
      },
      {
        trackTitle: "Give It Up, Turn It Loose",
        trackNumber: 8,
        duration: "5:10",
      },
      { trackTitle: "Yesterday", trackNumber: 9, duration: "2:30" },
      { trackTitle: "Hooked On Your Love", trackNumber: 10, duration: "3:35" },
      { trackTitle: "Love Don't Love You", trackNumber: 11, duration: "3:56" },
      { trackTitle: "What Is Love", trackNumber: 12, duration: "4:19" },
      { trackTitle: "Thanks/Prayer", trackNumber: 12, duration: "43" },
    ],
  },
  {
    albumTitle: "Sailing The Seas Of Cheese",
    releaseYear: 1991,
    artistName: "Primus",
    bandMembers: [
      { memberName: "Les Claypool" },
      { memberName: "Larry LaLonde" },
      { memberName: "Tim Alexander" },
      { memberName: "Jay Lane" },
      { memberName: "Mike Bordin" },
      { memberName: "Matt Winegar" },
      { memberName: "Tom Waits" },
      { memberName: "Trouz" },
    ],
    tracks: [
      { trackTitle: "Seas Of Cheese", trackNumber: 1, duration: "72" },
      {
        trackTitle: "Here Come The Bastards",
        trackNumber: 2,
        duration: "2:53",
      },
      { trackTitle: "Sgt. Baker", trackNumber: 3, duration: "4:13" },
      { trackTitle: "American Life", trackNumber: 4, duration: "4:31" },
      {
        trackTitle: "Jerry Was A Race Car Driver",
        trackNumber: 5,
        duration: "3:11",
      },
      { trackTitle: "Eleven", trackNumber: 6, duration: "4:18" },
      { trackTitle: "Is It Luck ?", trackNumber: 7, duration: "3:27" },
      { trackTitle: "Grandad's Little Ditty", trackNumber: 8, duration: "37" },
      { trackTitle: "Tommy The Cat", trackNumber: 9, duration: "4:14" },
      { trackTitle: "Sathington Waltz", trackNumber: 10, duration: "1:42" },
      {
        trackTitle: "Those Damned Blue-Collar Tweekers",
        trackNumber: 11,
        duration: "5:18",
      },
      {
        trackTitle: "Fish On (Fisherman Chronicles, Chapter II)",
        trackNumber: 12,
        duration: "7:45",
      },
      { trackTitle: "Los Bastardos", trackNumber: 12, duration: "2:39" },
    ],
  },
];
