const albums = [
  {
    albumTitle: "An Evening with Silk Sonic",
    releaseYear: 2021,
    artistName: "Silk Sonic",
    bandMembers: [
      { memberName: "Bruno Mars" },
      { memberName: "Anderson .Paak" },
    ],
    tracks: [
      { trackTitle: "Silk Sonic Intro", trackNumber: 1, trackDuration: "63" },
      {
        trackTitle: "Leave The Door Open",
        trackNumber: 2,
        trackDuration: "242",
      },
      { trackTitle: "Fly As Me", trackNumber: 3, trackDuration: "219" },
      { trackTitle: "After Last Night", trackNumber: 4, trackDuration: "249" },
      {
        trackTitle: "Smokin Out The Window",
        trackNumber: 5,
        trackDuration: "197",
      },
      { trackTitle: "Put On A Smile", trackNumber: 6, trackDuration: "255" },
      { trackTitle: "777", trackNumber: 7, trackDuration: "165" },
      { trackTitle: "Skate", trackNumber: 8, trackDuration: "203" },
      { trackTitle: "Love's Train", trackNumber: 9, trackDuration: "307" },
      { trackTitle: "Blast Off", trackNumber: 10, trackDuration: "284" },
    ],
  },
  {
    albumTitle: "Pearl",
    releaseYear: 1971,
    artistName: "Janis Joplin",
    bandMembers: [{ memberName: "" }],
    tracks: [
      { trackTitle: "Move Over", trackNumber: 1, trackDuration: "219" },
      { trackTitle: "Cry Baby", trackNumber: 2, trackDuration: "236" },
      {
        trackTitle: "A Woman Left Loney",
        trackNumber: 3,
        trackDuration: "207",
      },
      { trackTitle: "Half Moon", trackNumber: 4, trackDuration: "231" },
      {
        trackTitle: "Buried Alive In The Blues",
        trackNumber: 5,
        trackDuration: "144",
      },
      { trackTitle: "My Baby", trackNumber: 6, trackDuration: "244" },
      {
        trackTitle: "Me and Bobby McGee",
        trackNumber: 7,
        trackDuration: "269",
      },
      { trackTitle: "Mercedes Benz", trackNumber: 8, trackDuration: "106" },
      { trackTitle: "Trust Me", trackNumber: 9, trackDuration: "195" },
      {
        trackTitle: "Get It While You Can",
        trackNumber: 10,
        trackDuration: "203",
      },
    ],
  },
  {
    albumTitle: "Ain't That Good News",
    releaseYear: 1964,
    artistName: "Sam Cooke",
    bandMembers: [{ memberName: "" }],
    tracks: [
      {
        trackTitle: "Ain't That Good News",
        trackNumber: 1,
        trackDuration: "148",
      },
      {
        trackTitle: "Meet Me At Mary's Place",
        trackNumber: 2,
        trackDuration: "160",
      },
      { trackTitle: "Good Times", trackNumber: 3, trackDuration: "145" },
      {
        trackTitle: "Rome Wasn't Built In A Day",
        trackNumber: 4,
        trackDuration: "150",
      },
      {
        trackTitle: "Another Saturday Night",
        trackNumber: 5,
        trackDuration: "147",
      },
      { trackTitle: "Tennessee Waltz", trackNumber: 6, trackDuration: "190" },
      {
        trackTitle: "A Change Is Gonna Come",
        trackNumber: 7,
        trackDuration: "190",
      },
      { trackTitle: "Falling In Love", trackNumber: 8, trackDuration: "160" },
      { trackTitle: "Home", trackNumber: 9, trackDuration: "147" },
      {
        trackTitle: "Sittin' In The Sun",
        trackNumber: 10,
        trackDuration: "192",
      },
      { trackTitle: "No Second Time", trackNumber: 11, trackDuration: "180" },
      { trackTitle: "The Riddle Song", trackNumber: 12, trackDuration: "148" },
    ],
  },
  {
    albumTitle: "Greatest Hits",
    releaseYear: 2009,
    artistName: "Foo Fighters",
    bandMembers: [
      { memberName: "Dave Grohl" },
      { memberName: "Pat Smear" },
      { memberName: "Nate Mendel" },
      { memberName: "Taylor Hawkins" },
      { memberName: "Chris Shiflett" },
    ],
    tracks: [
      { trackTitle: "All My Life", trackNumber: 1, trackDuration: "264" },
      { trackTitle: "Best Of You", trackNumber: 2, trackDuration: "256" },
      { trackTitle: "Everlong", trackNumber: 3, trackDuration: "250" },
      { trackTitle: "The Pretender", trackNumber: 4, trackDuration: "268" },
      { trackTitle: "My Hero", trackNumber: 5, trackDuration: "259" },
      { trackTitle: "Learn To Fly", trackNumber: 6, trackDuration: "236" },
      { trackTitle: "Times Like These", trackNumber: 7, trackDuration: "268" },
      { trackTitle: "Monkey Wrench", trackNumber: 8, trackDuration: "233" },
      { trackTitle: "Big Me", trackNumber: 9, trackDuration: "134" },
      { trackTitle: "Breakout", trackNumber: 10, trackDuration: "202" },
      {
        trackTitle: "Long Road To Ruin",
        trackNumber: 11,
        trackDuration: "228",
      },
      { trackTitle: "This Is A Call", trackNumber: 12, trackDuration: "235" },
      { trackTitle: "Skin And Bones", trackNumber: 13, trackDuration: "244" },
      { trackTitle: "Wheels", trackNumber: 14, trackDuration: "278" },
      { trackTitle: "Word Forward", trackNumber: 15, trackDuration: "229" },
      {
        trackTitle: "Everlong (Acoustic)",
        trackNumber: 16,
        trackDuration: "251",
      },
    ],
  },
  {
    albumTitle: "Funky Divas",
    releaseYear: 1992,
    artistName: "En Vogue",
    bandMembers: [
      { memberName: "Terry Ellis" },
      { memberName: "Cindy Herron" },
      { memberName: "Maxine Jones" },
      { memberName: "Dawn Robinson" },
    ],
    tracks: [
      { trackTitle: "This Is Your Life", trackNumber: 1, trackDuration: "305" },
      {
        trackTitle: "My Lovin' (You're Never Gonna Get It)",
        trackNumber: 2,
        trackDuration: "282",
      },
      { trackTitle: "Hip Hop Lover", trackNumber: 3, trackDuration: "313" },
      { trackTitle: "Free Your Mind", trackNumber: 4, trackDuration: "292" },
      { trackTitle: "Desire", trackNumber: 5, trackDuration: "241" },
      {
        trackTitle: "Giving Him Something He Can Feel",
        trackNumber: 6,
        trackDuration: "236",
      },
      {
        trackTitle: "It Ain't Over Till The Fat Lady Sings",
        trackNumber: 7,
        trackDuration: "253",
      },
      {
        trackTitle: "Give It Up, Turn It Loose",
        trackNumber: 8,
        trackDuration: "310",
      },
      { trackTitle: "Yesterday", trackNumber: 9, trackDuration: "150" },
      {
        trackTitle: "Hooked On Your Love",
        trackNumber: 10,
        trackDuration: "215",
      },
      {
        trackTitle: "Love Don't Love You",
        trackNumber: 11,
        trackDuration: "236",
      },
      { trackTitle: "What Is Love", trackNumber: 12, trackDuration: "259" },
      { trackTitle: "Thanks/Prayer", trackNumber: 12, trackDuration: "43" },
    ],
  },
  {
    albumTitle: "Sailing The Seas Of Cheese",
    releaseYear: 1991,
    artistName: "Primus",
    bandMembers: [
      { memberName: "Les Claypool" },
      { memberName: "Larry LaLonde" },
      { memberName: "Tim Alexander" },
      { memberName: "Jay Lane" },
      { memberName: "Mike Bordin" },
      { memberName: "Matt Winegar" },
      { memberName: "Tom Waits" },
      { memberName: "Trouz" },
    ],
    tracks: [
      { trackTitle: "Seas Of Cheese", trackNumber: 1, trackDuration: "72" },
      {
        trackTitle: "Here Come The Bastards",
        trackNumber: 2,
        trackDuration: "173",
      },
      { trackTitle: "Sgt. Baker", trackNumber: 3, trackDuration: "253" },
      { trackTitle: "American Life", trackNumber: 4, trackDuration: "253" },
      {
        trackTitle: "Jerry Was A Race Car Driver",
        trackNumber: 5,
        trackDuration: "191",
      },
      { trackTitle: "Eleven", trackNumber: 6, trackDuration: "258" },
      { trackTitle: "Is It Luck ?", trackNumber: 7, trackDuration: "207" },
      {
        trackTitle: "Grandad's Little Ditty",
        trackNumber: 8,
        trackDuration: "37",
      },
      { trackTitle: "Tommy The Cat", trackNumber: 9, trackDuration: "254" },
      { trackTitle: "Sathington Waltz", trackNumber: 10, trackDuration: "102" },
      {
        trackTitle: "Those Damned Blue-Collar Tweekers",
        trackNumber: 11,
        trackDuration: "318",
      },
      {
        trackTitle: "Fish On (Fisherman Chronicles, Chapter II)",
        trackNumber: 12,
        trackDuration: "465",
      },
      { trackTitle: "Los Bastardos", trackNumber: 12, trackDuration: "159" },
    ],
  },
];
