name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      # Checkout repository
      - uses: actions/checkout@v1

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - name: Install Packages
        run: npm install --legacy-peer-deps

      # Update the homepage in package.json with the correct GitHub repository URL
      - name: Setup Homepage
        run: |
          sed -i 's|$HOMEPAGE|${{ github.repository }}|g' $GITHUB_WORKSPACE/package.json ; sed -i 's|${{ github.repository_owner }}/||g' $GITHUB_WORKSPACE/package.json

      # Build the page
      - name: Build page
        run: |
          cd packages/client  # Navigate to the client directory
          npm run build       # Run the build script for the client

      # List the contents of the dist folder for debugging
      - name: List dist folder content
        run: |
          cd packages/client  # Navigate to the client directory
          ls -al ./dist       # List contents of the dist folder

      # Deploy to GitHub Pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_TOKEN }}
          publish_dir: ./packages/client/dist  # Update to the correct dist directory
          user_name: "karenschick"
          user_email: "karenschick@users.noreply.github.com"
